"""
BrandLens Core Module

Exports core models, exceptions, and utilities for the BrandLens analyzer.
"""

from .models import (
    MentionType,
    ModelName,
    SearchDepth,
    CompressionMethod,
    SearchResult,
    LLMResponse,
    Citation,
    Mention,
    CompressedContent,
    BrandAnalysis,
    PerformanceMetrics,
    CacheEntry,
    APIConfig,
    CacheConfig,
    AppConfig,
)
from .exceptions import (
    BrandLensError,
    APIError,
    GeminiAPIError,
    TavilyAPIError,
    RateLimitError,
    QuotaExceededError,
    AuthenticationError,
    ValidationError,
    CompressionError,
    ExtractionError,
    ParsingError,
    CacheError,
    ConfigurationError,
    TimeoutError,
    InsufficientDataError,
    BrandAnalysisError,
    InvalidBrandError,
    SearchStrategyError,
    classify_error_for_retry,
    get_user_friendly_message,
    create_error_context,
)
from .metrics import MetricsCalculator

__all__ = [
    "MetricsCalculator",
    "MentionType",
    "ModelName",
    "SearchDepth",
    "CompressionMethod",
    "SearchResult",
    "LLMResponse",
    "Citation",
    "Mention",
    "CompressedContent",
    "BrandAnalysis",
    "PerformanceMetrics",
    "CacheEntry",
    "APIConfig",
    "CacheConfig",
    "AppConfig",
    "BrandLensError",
    "APIError",
    "GeminiAPIError",
    "TavilyAPIError",
    "RateLimitError",
    "QuotaExceededError",
    "AuthenticationError",
    "ValidationError",
    "CompressionError",
    "ExtractionError",
    "ParsingError",
    "CacheError",
    "ConfigurationError",
    "TimeoutError",
    "InsufficientDataError",
    "BrandAnalysisError",
    "InvalidBrandError",
    "SearchStrategyError",
    "classify_error_for_retry",
    "get_user_friendly_message",
    "create_error_context",
]
